CREATE TABLE family (
    id SERIAL PRIMARY KEY,
    father_special_needs BOOLEAN,
    father_name VARCHAR,
    father_phone_number VARCHAR,
    father_job INTEGER,
    father_education INTEGER,
    father_monthly_income INTEGER,
    father_status BOOLEAN,
    father_birth_date TIMESTAMP,
    father_birth_place VARCHAR,
    mother_special_needs BOOLEAN,
    mother_name VARCHAR,
    mother_phone_number VARCHAR,
    mother_job INTEGER,
    mother_education INTEGER,
    mother_monthly_income INTEGER,
    mother_status BOOLEAN,
    mother_birth_date TIMESTAMP,
    mother_birth_place VARCHAR,
    social_assistance_name_on_kip VARCHAR,
    social_assistance_kip_number VARCHAR,
    social_assistance_kps_kph_number VARCHAR,
    social_assistance_kip_recipient BOOLEAN,
    social_assistance_kps_kph_recipient BOOLEAN
);
