# .air.toml
[build]
cmd = "go build -o /app/tmp/main ./cmd/main.go"
bin = "/app/tmp/main"
watch_dir = "."
exclude_dir = ["tmp", "vendor", ".git"]
include_ext = ["go"]
exclude_ext = ["swp"]

[log]
level = "debug"
