services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    labels:
      - dev.orbstack.domains=api.sims-backend.local
    environment:
      DB_USER: ${BLUEPRINT_DB_USERNAME}
      DB_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
      DB_NAME: ${BLUEPRINT_DB_DATABASE}
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - .:/app
      - air-cache:/root/.air # Cache for Air
    command: ["air"] # Use hot-reloading
    working_dir: /app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${BLUEPRINT_DB_USERNAME}
      POSTGRES_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
      POSTGRES_DB: ${BLUEPRINT_DB_DATABASE}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  db-data:
  redis-data:
  rabbitmq-data:
  air-cache:
