services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"                         # Enable the dashboard (insecure mode for local testing)
      - "--providers.docker=true"                     # Enable Docker provider
      - "--providers.docker.exposedbydefault=false"   # Only expose containers with explicit labels
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/traefik_dynamic.yml"  # Load dynamic TLS configuration
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"    # Traefik dashboard available at http://localhost:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_dynamic.yml:/traefik_dynamic.yml:ro"
      - "./certs:/certs:ro"
    networks:
      - simsnet

  api:
    build: .
    container_name: sims-backend
    environment:
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.simsbe.test`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.domains[0].main=api.simsbe.test"
      - "traefik.http.routers.api.tls.domains[0].sans=api.simsbe.test"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - simsnet

  db:
    image: postgres:latest
    container_name: sims-postgres
    restart: always
    environment:
      POSTGRES_USER: melkey
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: blueprint
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - simsnet

  redis:
    image: redis:latest
    container_name: sims-redis
    ports:
      - "6379:6379"
    networks:
      - simsnet

  rabbitmq:
    image: rabbitmq:3-management:latest
    container_name: sims-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - simsnet

networks:
  simsnet:

volumes:
  db-data:
